services:
  ingestor:
    build:
      args:
        HEARTHLIGHT_IMAGE_VARIANT: cuda
        INGESTOR_BASE_IMAGE: anibali/pytorch:2.0.0-cuda11.8-ubuntu22.04
    gpus: all
    runtime: nvidia
    environment:
      - HEARTHLIGHT_IMAGE_VARIANT=cuda
      - NVIDIA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-all}

  association:
    build:
      args:
        HEARTHLIGHT_IMAGE_VARIANT: cuda
    environment:
      - HEARTHLIGHT_IMAGE_VARIANT=cuda

  anomaly:
    build:
      args:
        HEARTHLIGHT_IMAGE_VARIANT: cuda
    gpus: all
    runtime: nvidia
    environment:
      - HEARTHLIGHT_IMAGE_VARIANT=cuda
      - NVIDIA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-all}

  webapp:
    build:
      args:
        HEARTHLIGHT_IMAGE_VARIANT: cuda

  reset_db:
    build:
      args:
        HEARTHLIGHT_IMAGE_VARIANT: cuda
